'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('assert');
const ROOT=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),m=html.match(/\/\* CORE_START \*\/([\s\S]*?)\/\* CORE_END \*\//);assert(m);
const box={console,Math,Uint32Array,crypto:crypto.webcrypto};box.globalThis=box;vm.runInNewContext(m[1],box);const C=box.RiverCore;
const STYLES=['pressure','balanced','value','trap','nit'],STACKS=[5,10,15,25,40,60],BB=10;
const hash=(...xs)=>{let h=2166136261;for(const c of xs.join('|'))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const rng=seed=>{let x=seed>>>0;return max=>Math.floor(((x=Math.imul(x,1664525)+1013904223>>>0)/4294967296)*max)};
const row=()=>({hands:0,sbRaise:0,sbLimp:0,sbFold:0,bbFacingRaise:0,bbFold:0,bbCall:0,bb3bet:0,bbFacingLimp:0,bbCheck:0,bbIso:0,policyFallbacks:0});
function player(style,stack){return{style,stack,bet:0,total:0,folded:false,allIn:false,acted:false,lastActedBet:null,raiseRights:true,hole:[]}}
function post(st,i,n){let p=st.players[i],x=Math.min(n,p.stack);p.stack-=x;p.bet+=x;p.total+=x;st.pot+=x;if(!p.stack)p.allIn=true}
function context(st,i,seed){let p=st.players[i],L=C.legalActions(st,i),actions=st.actions.map(a=>({...a})),opener=actions.find(a=>a.street==='preflop'&&a.type==='raise'),other=st.players[1-i];return{actor:i,hole:p.hole.map(c=>({...c})),board:[],toCall:L.toCall,pot:st.pot,opponents:1,activeOpponents:1,position:i===0?1:0,positionName:i===0?'BTN':'BB',tableSize:2,inPosition:i===0,street:'preflop',raises:actions.filter(a=>a.type==='raise').length,stack:p.stack,effectiveStack:Math.min(p.stack,other.stack),spr:Math.min(p.stack,other.stack)/(st.pot||1),currentBet:st.currentBet,bb:BB,lastFullRaiseSize:st.lastFullRaiseSize,minRaiseTo:L.minRaiseTo,maxRaiseTo:L.maxRaiseTo,legalActions:{...L},actions,aggressor:opener?.actor??null,openerPosition:opener?'BTN':undefined,wasPreflopAggressor:false,opponentRange:opener?{preflopNode:'HU_SB',positionName:'BTN',tableSize:2,stack:Math.min(p.stack,other.stack),bb:BB}:actions.some(a=>a.type==='call')?{preflopNode:'HU_SB',positionName:'BTN',tableSize:2,stack:Math.min(p.stack,other.stack),bb:BB}:null,seed,humanModel:C.modelStats({})}}
function act(st,i,seed,tally){let L=C.legalActions(st,i),d=C.decideAction(st.players[i].style,context(st,i,seed)),type=d.type,to=d.to||0;if(type==='raise'&&L.canRaise)to=Math.min(L.maxRaiseTo,Math.max(L.minRaiseTo,Math.round(to/5)*5));else if(type==='fold'&&L.canFold){}else{if((type==='raise'&&!L.canRaise)||(type==='fold'&&!L.canFold)||(type==='call'&&!L.canCall)||(type==='check'&&!L.canCheck))tally.policyFallbacks++;type=L.toCall?'call':'check';to=0}let before=st.players[i].stack,potBefore=st.pot;C.applyAction(st,i,type,to);st.actions.push({street:'preflop',actor:i,position:i===0?'BTN':'BB',type,paid:before-st.players[i].stack,to:type==='raise'?to:st.players[i].bet,potBefore,allIn:st.players[i].allIn});return type}
function hand(stackBB,sbStyle,bbStyle,ordinal,tally){let stack=stackBB*BB,st={players:[player(sbStyle,stack),player(bbStyle,stack)],dealer:0,board:[],pot:0,lastPot:0,currentBet:0,lastFullRaiseSize:BB,actedSinceFullRaise:new Set(),turn:0,street:'preflop',actions:[]},deal=C.shuffledDeck(rng(hash(20260802,stackBB,sbStyle,bbStyle,ordinal,'deck')));st.players[0].hole=[deal.pop(),deal.pop()];st.players[1].hole=[deal.pop(),deal.pop()];post(st,0,5);post(st,1,10);st.currentBet=10;tally.hands++;let a=act(st,0,hash(20260802,stackBB,sbStyle,bbStyle,ordinal,'sb'),tally);if(a==='raise')tally.sbRaise++;else if(a==='call')tally.sbLimp++;else if(a==='fold')tally.sbFold++;if(a==='fold'||st.players[1].allIn)return;st.turn=1;if(a==='raise'){tally.bbFacingRaise++;let b=act(st,1,hash(20260802,stackBB,sbStyle,bbStyle,ordinal,'bb'),tally);if(b==='fold')tally.bbFold++;else if(b==='call')tally.bbCall++;else if(b==='raise')tally.bb3bet++}else{tally.bbFacingLimp++;let b=act(st,1,hash(20260802,stackBB,sbStyle,bbStyle,ordinal,'bb'),tally);if(b==='raise')tally.bbIso++;else if(b==='check')tally.bbCheck++}}
const cells={},overall=row(),HANDS_PER_PAIR=400;
for(const stack of STACKS)for(const s of STYLES)for(const b of STYLES){let r=row();for(let n=0;n<HANDS_PER_PAIR;n++)hand(stack,s,b,n,r);cells[`${stack}|${s}|${b}`]=r;for(const k of Object.keys(overall))overall[k]+=r[k]}
const pct=(n,d)=>d?+(100*n/d).toFixed(2):0,summary=r=>({...r,sbRaisePct:pct(r.sbRaise,r.hands),sbLimpPct:pct(r.sbLimp,r.hands),sbFoldPct:pct(r.sbFold,r.hands),bbFoldToRaisePct:pct(r.bbFold,r.bbFacingRaise),bbCallToRaisePct:pct(r.bbCall,r.bbFacingRaise),bb3betPct:pct(r.bb3bet,r.bbFacingRaise),bbIsoVsLimpPct:pct(r.bbIso,r.bbFacingLimp)});
const byStack={};for(const stack of STACKS){let r=row();for(const [k,v]of Object.entries(cells))if(k.startsWith(stack+'|'))for(const x of Object.keys(r))r[x]+=v[x];byStack[stack]=summary(r)}
const result={runAt:new Date().toISOString(),coreSha256:crypto.createHash('sha256').update(m[1]).digest('hex'),config:{handsPerPair:HANDS_PER_PAIR,personaPairs:25,stacksBB:STACKS,totalHands:overall.hands},overall:summary(overall),byStack};
fs.writeFileSync(path.join(__dirname,'postfix-preflop-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
